module.exports = {
  theme: {
    extend: {},
    fontFamily: {
      'sans': ['Montserrat'],
    }
  },
  variants: {
    accessibility: ['responsive', 'focus'],
    alignContent: ['responsive', 'hover', 'focus', 'group-hover'],
    alignItems: ['responsive', 'hover', 'focus', 'group-hover'],
    alignSelf: ['responsive', 'hover', 'focus', 'group-hover'],
    appearance: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundAttachment: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundPosition: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundRepeat: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundSize: ['responsive', 'hover', 'focus', 'group-hover'],
    borderCollapse: ['responsive', 'hover', 'focus', 'group-hover'],
    borderColor: ['responsive', 'hover', 'focus', 'group-hover'],
    borderRadius: ['responsive', 'hover', 'focus', 'group-hover'],
    borderStyle: ['responsive', 'hover', 'focus', 'group-hover'],
    borderWidth: ['responsive', 'hover', 'focus', 'group-hover'],
    boxShadow: ['responsive', 'hover', 'focus', 'group-hover'],
    cursor: ['responsive', 'hover', 'focus', 'group-hover'],
    display: ['responsive', 'hover', 'focus', 'group-hover'],
    fill: ['responsive', 'hover', 'focus', 'group-hover'],
    flex: ['responsive', 'hover', 'focus', 'group-hover'],
    flexDirection: ['responsive', 'hover', 'focus', 'group-hover'],
    flexGrow: ['responsive', 'hover', 'focus', 'group-hover'],
    flexShrink: ['responsive', 'hover', 'focus', 'group-hover'],
    flexWrap: ['responsive', 'hover', 'focus', 'group-hover'],
    float: ['responsive', 'hover', 'focus', 'group-hover'],
    fontFamily: ['responsive', 'hover', 'focus', 'group-hover'],
    fontSize: ['responsive', 'hover', 'focus', 'group-hover'],
    fontSmoothing: ['responsive', 'hover', 'focus', 'group-hover'],
    fontStyle: ['responsive', 'hover', 'focus', 'group-hover'],
    fontWeight: ['responsive', 'hover', 'focus', 'group-hover'],
    height: ['responsive', 'hover', 'focus', 'group-hover'],
    inset: ['responsive', 'hover', 'focus', 'group-hover'],
    justifyContent: ['responsive', 'hover', 'focus', 'group-hover'],
    letterSpacing: ['responsive', 'hover', 'focus', 'group-hover'],
    lineHeight: ['responsive', 'hover', 'focus', 'group-hover'],
    listStylePosition: ['responsive', 'hover', 'focus', 'group-hover'],
    listStyleType: ['responsive', 'hover', 'focus', 'group-hover'],
    margin: ['responsive', 'hover', 'focus', 'group-hover'],
    maxHeight: ['responsive', 'hover', 'focus', 'group-hover'],
    maxWidth: ['responsive', 'hover', 'focus', 'group-hover'],
    minHeight: ['responsive', 'hover', 'focus', 'group-hover'],
    minWidth: ['responsive', 'hover', 'focus', 'group-hover'],
    objectFit: ['responsive', 'hover', 'focus', 'group-hover'],
    objectPosition: ['responsive', 'hover', 'focus', 'group-hover'],
    opacity: ['responsive', 'hover', 'focus', 'group-hover'],
    order: ['responsive', 'hover', 'focus', 'group-hover'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive', 'hover', 'focus', 'group-hover'],
    padding: ['responsive', 'hover', 'focus', 'group-hover'],
    placeholderColor: ['responsive', 'focus'],
    pointerEvents: ['responsive', 'hover', 'focus', 'group-hover'],
    position: ['responsive', 'hover', 'focus', 'group-hover'],
    resize: ['responsive', 'hover', 'focus', 'group-hover'],
    stroke: ['responsive', 'hover', 'focus', 'group-hover'],
    tableLayout: ['responsive', 'hover', 'focus', 'group-hover'],
    textAlign: ['responsive', 'hover', 'focus', 'group-hover'],
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    textDecoration: ['responsive', 'hover', 'focus', 'group-hover'],
    textTransform: ['responsive', 'hover', 'focus', 'group-hover'],
    userSelect: ['responsive', 'hover', 'focus', 'group-hover'],
    verticalAlign: ['responsive', 'hover', 'focus', 'group-hover'],
    visibility: ['responsive', 'hover', 'focus', 'group-hover'],
    whitespace: ['responsive', 'hover', 'focus', 'group-hover'],
    width: ['responsive', 'hover', 'focus', 'group-hover'],
    wordBreak: ['responsive', 'hover', 'focus', 'group-hover'],
    zIndex: ['responsive', 'hover', 'focus', 'group-hover'],
  },
  plugins: []
}
